from PIL import Image , ImageEnhance , ImageFilter
import os
# brightness (0)
img1 = Image.open('captain america 1.jpg')
enhancer = ImageEnhance.Brightness(img1)
enhancer.enhance(0).save('edicted0.png')
# brightness (1)
img1 = Image.open('captain america 1.jpg')
enhancer = ImageEnhance.Brightness(img1)
enhancer.enhance(1).save('edicted1.png')
# brightness (2)
img1 = Image.open('pic.jpg')
enhancer = ImageEnhance.Brightness(img1)
enhancer.enhance(2).save('edicted2.png')
# sharpness (0)
img1 = Image.open('captain america 1.jpg')
enhancer = ImageEnhance.Sharpness(img1)
enhancer.enhance(0).save('edicted3.png')
# sharpness (6)
img1 = Image.open('captain america 1.jpg')
enhancer = ImageEnhance.Sharpness(img1)
enhancer.enhance(6).save('edicted4.png')
# color (0)
img1 = Image.open('captain america 1.jpg')
enhancer = ImageEnhance.Color(img1)
enhancer.enhance(0).save('edicted5.png')
# color (1)
img1 = Image.open('captain america 1.jpg')
enhancer = ImageEnhance.Color(img1)
enhancer.enhance(1).save('edicted6.png')
# color (2)
img1 = Image.open('captain america 1.jpg')
enhancer = ImageEnhance.Color(img1)
enhancer.enhance(4).save('edicted7.png')
# contrast (3)
img1 = Image.open('captain america 1.jpg')
enhancer = ImageEnhance.Contrast(img1)
enhancer.enhance(3).save('edicted8.png')

img1 = Image.open('captain america 1.jpg')
img1.filter(ImageFilter.GaussianBlur()).save('edited9.png')
